# Generated by Django 5.2.7 on 2025-10-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('sexe', models.CharField(choices=[('M', 'Monsieur'), ('F', 'Madame')], max_length=1, verbose_name='Sexe')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('cin_date', models.DateField(verbose_name='Date délivrance CIN')),
                ('cin_lieu', models.CharField(max_length=100, verbose_name='Lieu délivrance CIN')),
                ('adresse', models.CharField(max_length=200, verbose_name='Adresse')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('contrat_cdi', models.BooleanField(default=False, verbose_name='CDI')),
                ('en_poste', models.BooleanField(default=True, verbose_name='Toujours en poste')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif')),
                ('approuve', models.BooleanField(default=True, verbose_name='Approuvé')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='attestations.employe')),
            ],
            options={
                'verbose_name': 'Congé',
            },
        ),
        migrations.CreateModel(
            name='PosteHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150, verbose_name='Intitulé du poste')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='attestations.employe')),
            ],
            options={
                'verbose_name': 'Historique de poste',
                'ordering': ['date_debut'],
            },
        ),
    ]
