# Generated by Django 5.2.7 on 2025-12-01 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_conge', models.DateField()),
                ('date_fin_conge', models.DateField()),
                ('type_conge', models.CharField(max_length=100)),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestations.employe')),
            ],
        ),
        migrations.CreateModel(
            name='AttestationTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestations.employe')),
            ],
        ),
        migrations.CreateModel(
            name='CertificatTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateField()),
                ('motif_sortie', models.TextField(blank=True, null=True)),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestations.employe')),
            ],
        ),
    ]
