# Generated by Django 5.2.7 on 2026-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0003_employe_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postehistorique',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Historique de poste'},
        ),
        migrations.AlterField(
            model_name='conge',
            name='approuve',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
